sudo: required

language: node_js
node_js:
  - "7"

services:
  - docker

before_install:
  - docker built -t opendronemap/node-opendronemap .
  - docker run opendronemap/node-opendronemap /bin/sh -c "cd /var/www; node index.js --powercycle"

script: node index.js --powercycle
